name: tests

on: push

jobs:
  cover_tests:
    name: Cover Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Setup Node 10
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache Dependencies
      id: cache-node-modules
      uses: actions/cache@v1
      env:
        cache-version: 1
      with:
        path: node_modules
        key: v${{ env.cache-version }}-node10-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: |
        echo "//npm.pkg.github.com/:_authToken=${{ secrets.AUTH_TOKEN }}" > ~/.npmrc
        npm ci

    - name: Lint
      run: npx standard

    - name: Cover Tests
      run:
        npm run test:cover

    - name: Publish Coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: coverage/lcov.info

  node_12_tests:
    name: Node 12 Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Setup Node 12
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache Dependencies
      id: cache-node-modules
      uses: actions/cache@v1
      env:
        cache-version: 1
      with:
        path: node_modules
        key: v${{ env.cache-version }}-node12-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: |
        echo "//npm.pkg.github.com/:_authToken=${{ secrets.AUTH_TOKEN }}" > ~/.npmrc
        npm ci

    - name: Test Node
      run: npm run test